chassis:
  update_rate: 500
  timeout: 0.1
  accel:
    x: 1.0
    y: 1.0
    w: 1.0
  wheelsets:
    left_front:
      position: [ 0.557, 0.585 ]
      steer: 
        direction: 1.0
      roll:
        direction: 1.0  
        radius: 0.1175
    # right_front:
    #   position: [ 0.557, -0.585 ]
    #   steer: 
    #     direction: 1.0
    #   roll:
    #     direction: -1.0  
    #     radius: 0.1175
    # left_back:
    #   position: [ -0.557, 0.585 ]
    #   steer: 
    #     direction: 1.0
    #   roll:
    #     direction: 1.0  
    #     radius: 0.1175
    # right_back:
    #   position: [ -0.557, -0.585 ]
    #   steer: 
    #     direction: 1.0
    #   roll:
    #     direction: -1.0  
    #     radius: 0.1175