/:
    # Publish all joint states -----------------------------------
    # 以下控制器由ros_control功能包提供
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000

    # Controllers ---------------------------------------
    # 以下控制器由ros_control功能包提供
    # JointPositionController:位置环控制
    # JointVelocityController:速度环
    # JointEffortController电流环(无PID)

    # 轮毂电机控制速度环,曲柄电机和转向电机控制位置环
    LF0_controller:
        type: effort_controllers/JointVelocityController
        joint: LF0_Joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    RF0_controller:
        type: effort_controllers/JointVelocityController
        joint: RF0_Joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    LB0_controller:
        type: effort_controllers/JointVelocityController
        joint: LB0_Joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    RB0_controller:
        type: effort_controllers/JointVelocityController
        joint: RB0_Joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    LF2_controller:
        type: effort_controllers/JointPositionController
        joint: LF2_Joint
        pid: {p: 40.0, i: 0.0, d: 0.5}

    RF2_controller:
        type: effort_controllers/JointPositionController
        joint: RF2_Joint
        pid: {p: 40.0, i: 0.0, d: 0.5}

    LB2_controller:
        type: effort_controllers/JointPositionController
        joint: LB2_Joint
        pid: {p: 40.0, i: 0.0, d: 0.5}

    RB2_controller:
        type: effort_controllers/JointPositionController
        joint: RB2_Joint
        pid: {p: 40.0, i: 0.0, d: 0.5}

