# unit：m/s
x_vel: 0.5
y_vel: 0.5
turn: 0.2
x_vel_limit: 2
y_vel_limit: 2
turn_limit: 1

repeat_rate: 0.0
key_timeout: 0.5



# x_vel: 0.5
# y_vel: 0.5
# turn: 0.2
# max_x_vel: 2
# max_y_vel: 2
# max_turn: 1
# x_acc: 0.1
# y_acc: 0.1
# turn_acc: 0.02
