port_name: "/dev/ttyUSB1"  # 串口控制权限在/etc/udev/rules.d/70-ttyusb.rules中
reduction_ratio: 9   # 减速比
motor_ctrl_data:
  mode: 10    # 自定义默认控制方式：空闲==0，开环==5，FOC闭环控制==10
  ctrl_frequency: 200   # 控制频率

  #FOC闭环控制参数
  pos_kp_kw: [0.1, 3.0] # 位置模式下的关节刚度、速度系数。PD控制，kp为比例系数，kw为微分系数
  vel_kp_kw: [0.0, 3.0] # 速度模式下的关节刚度、速度系数。kp需为0，kw为比例系数
  trq_kp_kw: [0.0, 0.0] # 力矩模式下的关节刚度、速度系数，均为0
  traj_kp_kw: [0.05, 5.0] # 轨迹规划模式下的关节刚度、速度系数。PD控制，kp为比例系数，kw为微分系数

  #目标角度：°    目标速度：rad/s   目标力矩：NM
  goal_pos_vec: [22.5, 45.0, 90.0, 180.0] 
  goal_vel: 10
  goal_trq: 0.07
  goal_traj: [90, 90, 90, -90, 90, -90]  # 路点